services:
  watcharr:
    # The :latest tag is used for simplicity, it is recommended
    # to use an actual version, then when updating check the releases for changelogs.
    image: mazurkatarzyna/cve-2024-50634:latest
    container_name: watcharr
    ports:
      - 50634:3080
    volumes:
      # Contains all of watcharr data (database & cache)
      - ./data:/data
    restart: unless-stopped
